---
title: "Multi-omics data integration: MOMS-PI example"
author: "Margaret Turner"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Multi-omics data integration: MOMS-PI example}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, message = FALSE}
library(tidyverse)
library(MultiAssayExperiment)
library(TidyMultitude)
library(ade4)
library(knitr)
library(kableExtra)
```

This vignette reproduces the **Multi-omics data integration: MOMS-PI example** section from the [Working with open-source Human Microbiome Project Data phases 1 (HMP) and 2 (iHMP): Efficient Data Access and Analysis Workflow](http://biocworkshops2019.bioconductor.org.s3-website-us-east-1.amazonaws.com/page/MicrobiomeWorkshop__MicrobiomeWorkshop/) workshop, demonstrating how the pre-processing steps can be simplified using `TidyMultitude`. 

```{r}
data("momspiCyto_mtx")
data("momspiCyto_samp")
momspiCyto <- SummarizedExperiment(assays = list(cyto_conc = momspiCyto_mtx),
                                   colData = momspiCyto_samp,
                                   rowData = data.frame(cytokine = 
                                                        rownames(momspiCyto_mtx)))
```



```{r}
data("momspi16S_mtx")
data("momspi16S_samp")
data("momspi16S_tax")
momspi16S <- SummarizedExperiment(assays = list(counts = momspi16S_mtx),
                                  colData = momspi16S_samp,
                                  rowData = momspi16S_tax)
```


```{r}
momspi_data <- MultiAssayExperiment(experiments = list(phy16S = momspi16S,
                                                       cyto = momspiCyto))
```


```{r}
# Define my preprocessing function
prep <- function(data, scale = c(TRUE, FALSE)){
  # Note that the data is transposed so that these steps are performed rowwise
  scaled <- scale(t(data), center = TRUE, scale = scale) # Center and scale
  tr <- sum(scaled * scaled)/(dim(scaled)[1]-1) # Fast trace computation
  processed <- scaled/sqrt(tr) # Normalize magnitude
  return(t(processed)) # Rotate back
}
```



```{r}
pca_list <- momspi_data %>% 
  # Order both sets by visit number within a subject
  arrange_colData(subject_id, sample_body_site, visit_number) %>% 
  # Use metadata to select data collected at
  # (1) the same visit (across the two experiments)
  intersect_colData(by = c("subject_id", "sample_body_site",
                           "project_name", "study_full_name", "subject_gender",
                           "subject_race", "visit_number")) %>% 
  # and (2) the first visit
  filter_colData(visit_number == 1) %>% 
  # Remove OTUs not observed in any subject
  trim_empty_rows(phy16S) %>% 
  # For phy16S data: Convert taxa to proportions
  # Then, by row -- center (but do not scale) and normalize magnitude
  transmute(phy16S,
            cov = (t(counts)/colSums(counts))%>% 
              t() %>% 
              prep(., scale = FALSE)) %>% 
  # For cytokines data: by row -- center, 
  transmute(cyto,
            corr = prep(cyto_conc, scale = TRUE)) %>% 
  assays() %>% 
  # Ensure that samples are in rows, variables are in columns
  lapply(., t) %>% 
  # Perform PCA on both experiments
  lapply(., function(x) {
    ade4::dudi.pca(x, scannf = FALSE, nf = 61, 
                   center = FALSE, scale = FALSE)
  })
```


```{r}
coin <- ade4::coinertia(dudiX = pca_list[["phy16S"]], dudiY = pca_list[["cyto"]], 
                        scannf = FALSE, nf = 2)
coin$RV
```

```{r}
kable(head(coin$co),
      digits = 5)%>%
  kable_styling(bootstrap_options = c("striped", "hover"), full_width = F)
```


```{r}
kable(head(coin$li),
      digits = 5)%>%
  kable_styling(bootstrap_options = c("striped", "hover"), full_width = F)
```

```{r}

```

